kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test

- name: publish
  image: plugins/docker
  settings:
    repo: drone/node-demo
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dry_run: true

trigger:
  branch:
  - master
