kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test

- name: publish
  image: plugins/docker
  repo: drone/node-demo
  secrets: [ docker_username, docker_password ]
  dry_run: true

trigger:
  branch:
  - master
